[package]
name = "catsec"
version = "0.3.9-Pre"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.2"
rpassword = "0.0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"