[package]
name = "catsec"
version = "0.3.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
rpassword = "0.0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"